version: "3.3" # optional since v1.27.0
services:
  service_nginx_proxy:
    build:
      context: .
      dockerfile: nginx_proxy.Dockerfile
    image: nggit/addr-nginx-proxy
    container_name: service_nginx_proxy
    restart: unless-stopped
    volumes:
      - ./ssh_server/config/data:/app/data # share ssh_server data to nginx service
      - ./nginx:/etc/nginx
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host
  service_ssh_server:
    build:
      context: .
      dockerfile: ssh_server.Dockerfile
    image: nggit/addr-ssh-server
    container_name: service_ssh_server
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - AUDIT_WRITE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - NET_BIND_SERVICE
      - SETFCAP
      - SETGID
      - SETUID
    volumes:
      - ./ssh_server:/app/ssh_server
    network_mode: host
